### ISSUE TITLE
Where is [drupal-security-checklist]

### ISSUE THREAD

**Issue by greggles** [gfoss/attacking-drupal#1]
The README mentions this but I don't see it in the scripts or videos.

I am interested in it, of course :)

I'm also curious if/how it differs from https://drupal.org/project/security_review and https://drupal.org/project/paranoia

**Comment by gfoss** [comment]
The checklist is located within the /presentation/ directory. Sorry, I probably should have listed that within the readme.

This is different in that it is not a Drupal module, though it does list the security review module as a recommendation. It's essentially a short document listing commonly miss-configured items that developers should take into account when building a Drupal web application / for security professionals to assist with the assessment of said applications.

I did not include paranoia as I have never actually seen this in use on any production sites, plus I want to try and keep this one-page if possible.  ;-)

**Comment by greggles** [comment]
Oh, awesome. Looks good. 

I'd say that I've never seen password_policy used on a production site ;) Maybe replace that (or augment it) with http://drupal.org/project/tfa ? That might even leave space for Paranoia which is used [a](http://www.acquia.com/sites/all/modules/contrib/paranoia/README.txt) [bit](https://drupal.org/sites/all/modules/paranoia/README.txt).

**Comment by gfoss** [comment]
Good idea! I'll take a look and see if I can squeeze these ones in there. May just need to trim the fat elsewhere to make room for more important resources such as the two you've mentioned.

**Comment by gfoss** [comment]
Sorry for the delay, haven't been playing with Drupal as much lately as I'd like to... I've updated the checklist.
